site_name: Image Generation Workspace Documentation
site_description: Comprehensive documentation for AI image generation projects, tools, and resources
site_url: https://your-username.github.io/image-generation-workspace
repo_url: https://github.com/your-username/image-generation-workspace
repo_name: image-generation-workspace
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Components:
    - Architecture: components/architecture.md
    - Anime Wallpaper Remaster: components/anime-wallpaper-remaster.md
    - LibreChat Integration: components/librechat.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Authentication: api/authentication.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Deployment:
    - Docker: deployment/docker.md
    - Kubernetes: deployment/kubernetes.md
    - Cloud: deployment/cloud.md
  - Security:
    - Overview: security/overview.md
    - Threat Model: security/threat-model.md
    - Best Practices: security/best-practices.md
  - Reference:
    - Configuration: reference/configuration.md
    - Troubleshooting: reference/troubleshooting.md
    - FAQ: reference/faq.md

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - footnotes

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/image-generation-workspace
    - icon: fontawesome/brands/docker
      link: https://github.com/your-username/image-generation-workspace/pkgs/container/image-generation-workspace
  analytics:
    provider: google
    property: G-XXXXXXXXXX

extra_css:
  - stylesheets/extra.css
